POST http://localhost:4000/box/share
Content-Type: application/json

{
    "share":"test2",
    "code":"31556082"
}

###

GET http://localhost:4000/box/shares
Content-Type: application/json

{
    "code":"31556082"
}

###
POST http://localhost:4000/register 
Content-Type: application/json

{
    "name":"test11",
    "email":"test11",
    "password":"test11"
}

###

POST http://localhost:4000/login
Content-Type:application/json

{
    "email":"test11",
    "password":"test11"
}

### 

GET http://localhost:4000/user

###

GET http://localhost:4000/

###

POST http://localhost:4000/box/delete
Content-Type: application/json

{"id":"1234"}